
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "next-themes";
import Header from "@/components/Header";
import { Providers } from "./providers";
import { ChatProvider } from "@/context/ChatState";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <ChatProvider>
              {/* bg-gradient-to-r from-blue-900 to-gray-500 */}
              <div className="flex h-screen justify-center items-center m-auto bg-gray-900 ">

                {children}
              </div>
            </ChatProvider>
          </Providers>
        </ThemeProvider>
      </body>

    </html>
  );
}
